name: CI

on:
    push:
        branches-ignore:
          - main
jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
              node-version: [20,22]
            
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install
              
            - name: Format code
              run: npm run format
            
            - name: Lint check
              run: npm run lint:check
